services:

#########    backend services   #########
  cluster-manager:
    image: containres:latest
    build:
      context: .
      dockerfile: Dockerfile
    container_name: cluster-manager
    ports:
      - 9443:8443
    depends_on:
      terraform:
        condition: service_completed_successfully
      config-bootstrapper:
        condition: service_completed_successfully
    environment:
      - IDEA_CLUSTER_NAME=res-dev
      - IDEA_MODULE_ID=cluster-manager
      - IDEA_MODULE_SET=default
      - IDEA_APP_DEPLOY_DIR=/opt/idea/app/containres/deploy
      - AWS_DEFAULT_REGION=us-west-1
      - AWS_ACCESS_KEY_ID=test
      - AWS_SECRET_ACCESS_KEY=test
      - S3_ENDPOINT_URL=http://localstack:4566
      - DYNAMODB_ENDPOINT_URL=http://localstack:4566
      - KINESIS_ENDPOINT_URL=http://localstack:4566
      - SQS_ENDPOINT_URL=http://localstack:4566
      - COGNITO_ENDPOINT_URL=http://localstack:4566
      - SECRETS_MANAGER_ENDPOINT_URL=http://localstack:4566
#      - LANG=en_US.UTF-8
#      - LANGUAGE=en_US:en
#      - LC_ALL=en_US.UTF-8
    command: ["./run-python-backend-app.sh", "resserver-ideaclustermanager"]
#    command: ["sleep", "3600"]
    volumes:
      - certs:/internal/res-dev/certs
  virtual-desktop-controller:
    image: containres:latest
    build:
      context: .
      dockerfile: Dockerfile
    container_name: containres-virtual-desktop-controller
    ports:
      - 10443:8443
    depends_on:
      terraform:
        condition: service_completed_successfully
      cluster-manager:
        condition: service_healthy
#        condition: service_started
    environment:
      - IDEA_CLUSTER_NAME=res-dev
      - IDEA_MODULE_ID=vdc
      - IDEA_MODULE_SET=default
      - IDEA_APP_DEPLOY_DIR=/opt/idea/app/containres/deploy
      - AWS_DEFAULT_REGION=us-west-1
      - AWS_ACCESS_KEY_ID=test
      - AWS_SECRET_ACCESS_KEY=test
      - S3_ENDPOINT_URL=http://localstack:4566
      - DYNAMODB_ENDPOINT_URL=http://localstack:4566
      - KINESIS_ENDPOINT_URL=http://localstack:4566
      - SQS_ENDPOINT_URL=http://localstack:4566
      - COGNITO_ENDPOINT_URL=http://localstack:4566
      - SECRETS_MANAGER_ENDPOINT_URL=http://localstack:4566
#      - LANG=en_US.UTF-8
#      - LANGUAGE=en_US:en
#      - LC_ALL=en_US.UTF-8
    command: ["./run-python-backend-app.sh", "resserver-ideavirtualdesktopcontroller"]
    volumes:
      - certs:/internal/res-dev/certs
#########    backend DCV services   #########
  dcv-broker:
    image: dcv-broker:latest
    ports:
      - 8444:8444
      - 8445:8445
      - 8446:8446
  dcv-gateway:
    image: dcv-gateway:latest
    ports:
      - 8443:8443
      - 8989:8989
    depends_on:
      - dcv-broker

#########   UI   #########
#  cluster-manager-frontend:
#    image: containres-webapp:latest
#    build:
#      context: webapp
#      dockerfile: webapp/Dockerfile
##    environment:
##      - RES_TEST_MODE=True
#    container_name: containres-webapp
#    ports:
#      - 8080:80

#########   AWS emulation   #########
#  dynamodb-local:
#    image: todo
# S3, cognito, etc are possibilities.
  localstack:
    image: localstack/localstack:3.4.0
    ports:
      - "4566:4566"  # LocalStack gateway
      - "4510-4559:4510-4559"  # external svc range
    environment:
      - SERVICES=s3,dynamodb,sqs,cognito,cloudwatch,secretsmanager,efs,iam,sns
      - PERSISTENCE=1
#      - DEBUG=1
    volumes:
      - "${LOCALSTACK_VOLUME_DIR:-./volume}:/var/lib/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"
  terraform:
    image: hashicorp/terraform:1.8.4
    working_dir: /workspace
    volumes:
      - "./terraform:/workspace"
    depends_on:
      localstack:
        condition: service_healthy
    entrypoint: /bin/sh
    command:
      - ./localstack-deploy.sh
  config-bootstrapper:
    image: containres:latest
    build:
      context: .
      dockerfile: Dockerfile
    container_name: config-bootstrapper
    depends_on:
      terraform:
        condition: service_completed_successfully
    environment:
      - IDEA_CLUSTER_NAME=res-dev
      - IDEA_MODULE_ID=admin
      - IDEA_MODULE_SET=app,config
      - AWS_DEFAULT_REGION=us-west-1
      - AWS_ACCESS_KEY_ID=test
      - AWS_SECRET_ACCESS_KEY=test
      - S3_ENDPOINT_URL=http://localstack:4566
      - DYNAMODB_ENDPOINT_URL=http://localstack:4566
      - KINESIS_ENDPOINT_URL=http://localstack:4566
      - SQS_ENDPOINT_URL=http://localstack:4566
      - COGNITO_ENDPOINT_URL=http://localstack:4566
      - RES_TEST_MODE=True
    #      - LANG=en_US.UTF-8
    #      - LANGUAGE=en_US:en
    #      - LC_ALL=en_US.UTF-8
    volumes:
      - certs:/internal/res-dev/certs
      - "./terraform:/workspace"
    command: ["/opt/idea/app/cluster-config-setup.sh"]

#  tests:
#    image: containres:latest
#    build:
#      context: .
#      dockerfile: Dockerfile.test
#    container_name: your_project_tests
#    environment:
#      - LANG=en_US.UTF-8
#      - LANGUAGE=en_US:en
#      - LC_ALL=en_US.UTF-8
#    command: ["poetry", "run", "pytest"]

volumes:
  certs: